export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';
export const UNAUTHORIZED_REDIRECT = 'UNAUTHORIZED_REDIRECT';
export const UPDATE_USER_BASIC_PROFILE = 'UPDATE_USER_BASIC_PROFILE';
export const UPDATE_PROFILE_IMAGE = 'UPDATE_PROFILE_IMAGE';
export const UPDATE_PIN = 'UPDATE_PIN';
export const PHONE_VERIFICATION = 'PHONE_VERIFICATION';

export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';

export const UPDATE_ORDER_STATUS = 'UPDATE_ORDER_STATUS';
export const UPDATE_ORDER_RIDER_INFO = 'UPDATE_ORDER_RIDER_INFO';
export const UPDATE_ORDER_RIDER_LOCATION = 'UPDATE_ORDER_RIDER_LOCATION';
export const SAVE_ALL_ORDERS_TO_REDUX = 'SAVE_ALL_ORDERS_TO_REDUX';
export const SAVE_ORDER_TO_REDUX = 'SAVE_ORDER_TO_REDUX';
export const SELECT_ORDER_TO_VIEW = 'SELECT_ORDER_TO_VIEW';
export const CLEAR_LATEST_ORDER = 'CLEAR_LATEST_ORDER';

export const POST_FCM_TOKEN = 'POST_FCM_TOKEN';
export const PATCH_FCM_TOKEN = 'PATCH_FCM_TOKEN';
