export const ORDER_STATUS = {
  WAITING_MERCHANT_CONFIRM: 'waiting_merchant_confirm',
  WAITING_RIDER_CONFIRM: 'waiting_rider_confirm',
  WAITING_GATEWAY_CONFIRM: 'waiting_gateway_confirm',
  MERCHANT_PREPARING: 'merchant_preparing',
  RIDER_PICKING_UP: 'rider_picking_up',
  RIDER_PICKED_UP: 'rider_picked_up',
  ARRIVE_HUB: 'arrive_hub',
  HUB_TRANSFER: 'hub_transfer',
  DELIVERING: 'delivering',
  DELIVERED: 'delivered',
  CANCELLED_BY_CONSUMER: 'cancelled_by_consumer',
  CANCELLED_BY_PLATFORM: 'cancelled_by_platform',
  CANCELLED_BY_PAYMENT_SYSTEM: 'cancelled_by_payment_system',
  DECLINED_BY_MERCHANT: 'declined_by_merchant',
  CONSUMER_PICKED_UP: 'consumer_picked_up',
  FORCE_ASSIGN_FAILED: 'force_assign_failed',
  HANDLED_BY_ADMIN: 'handled_by_admin',
  HANDLED_BY_THIRD_PARTY_COURIER_SERVICE:
    'handled_by_third_party_courier_service',
  CREATED: 'created',
  WAITING_RIDER_PICK_UP: 'waiting_rider_pick_up',
  RETURN_TO_HUB: 'return_to_hub',
};
